### ISSUE TITLE
Checklist for supported tags

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/YANG-to-Redfish-Converter#26]
- [ ] 6 YANG statement mapping format
- [ ] **6.1.5 Namespace**
- [ ] 6.2.1 Belongs-to 
- [ ] 6.4.2 Path 
- [ ] 6.4.3 require-instance 
- [ ] 6.4.4 Mapping special types
- [ ] 6.8.3 Key 
- [ ] **6.10 Anyxml**
- [ ] 6.12.1 Refine 
- [ ] 6.13 Rpc 
- [ ] 6.13.2 Input 
- [ ] 6.13.3 Output 
- [ ] **6.14 Notification**
- [ ] 6.16.2 Base 
- [ ] **6.17 Extension** 
- [ ] **6.18 Argument** 
- [x] 6.1 Module 
- [x] 6.1.3 Import
- [x] 6.1.4 Include 
- [x] **6.1.6 Prefix**
- [x] **6.2 Submodule**
- [x] 6.3 Typedef 
- [x] 6.3.2 Default 
- [x] 6.4 Type 
- [x] 6.5 Container 
- [x] 6.6 Leaf 
- [x] 6.7 Leaf-list 
- [x] 6.8 List 
- [x] 6.9 Choice 
- [x] 6.9.3 Case
- [x] 6.11 Grouping 
- [x] 6.12 Uses 
- [x] 6.15 Augment 
- [x] **6.16 Identity**
- [x] **6.21 Deviation** 
- [x] **6.22 Deviate** 
- [x] **6.23 Config**
- [x] **6.24 Status**
- [x] 6.19 Feature 
- [x] 6.20 If-feature 
- [x] 6.25 Description 
- [x] 6.26 Reference 
- [x] 6.27 When 
- [x] 6.28 Unmapped YANG statements
- [ ] Property keywords related to CSDL int ranges, regex patterns...

Checklist in progress of being filled out, some of which might already be covered but are unchecked. 
 Anything in bold would might need to be double check.
